version: '3.1'

services:

  nginx:
    container_name: phpproject-nginx
    build:
      context: ./docker/config/nginx
    ports:
      - 8000:80
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: phpproject-php
    build:
      context: ./docker/config/php
    ports:
      - 9000:9000
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./docker/config/php/php.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini # PHP FPM
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/docker-php-zzz-overrides.ini # PHP Client
